# Placeholder, uses defaults
faascinator:
  description: "Demonstrates usage of FaaScinator with external CLI App JAR (CheckSum calculator)"
  mainClass: "io.faascinator.demo.picocli.CheckSum"
  cliJar: "../3_demo_picocli/target/demo-picocli.jar"
