# Placeholder, uses defaults
quarkus:
  faascinator:
    description: "Demonstrates usage of FaaScinator with external CLI App JAR (CheckSum calculator)"
    mainClass: "io.faascinator.demo.picocli.CheckSum"
    cliJar: "../8_demo-picocli/target/demo-picocli.jar"
