
# Automates creation of changelog drafts using Release Drafter
# More info: https://github.com/release-drafter/release-drafter
# Inspired by: Jenkins community, https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
name: Changelog Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - name: Generate GitHub Release Draft
        id: release-drafter
        uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
